#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef STAYONFRAMEWORK_SWIFT_H
#define STAYONFRAMEWORK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreBluetooth;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="StayOnFramework",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// 接口异常信息
/// API Error Information
typedef SWIFT_ENUM(NSInteger, APIErrorCode, open) {
/// 网络异常
/// Network Error
  APIErrorCodeApiError = 400001,
/// 解析异常
/// Parsing Error
  APIErrorCodeCodeError = 400002,
/// 数据异常
/// Data Error
  APIErrorCodeDataError = 400003,
/// 缺少参数
/// Missing Parameters
  APIErrorCodeParamError = 400004,
/// 签名校验失败
/// Signature Verification Failed
  APIErrorCodeSignError = 400005,
/// 查找的信息不存在
/// Requested Data Not Found
  APIErrorCodeNoDataError = 400006,
/// token不存在
/// Token Not Found
  APIErrorCodeNoTokenError = 400007,
/// token失效
/// Token Expired
  APIErrorCodeTokenError = 400008,
};

/// 设备测量状态报警枚举
/// Device measurement status alarm enumeration
typedef SWIFT_ENUM(NSInteger, CGMAlarmCode, open) {
/// 位0：设备电量低
/// Bit 0: Low device battery
  CGMAlarmCodeLowBattery = 0,
/// 位1：温度过高
/// Bit 1: High temperature
  CGMAlarmCodeHighTemperature = 1,
/// 位2：温度过低
/// Bit 2: Low temperature
  CGMAlarmCodeLowTemperature = 2,
/// 位3：AFE异常
/// Bit 3: AFE error
  CGMAlarmCodeAfeError = 3,
/// 位4：电流过大/过小失效
/// Bit 4: Current too high/too low failure
  CGMAlarmCodeCurrentAbnormal = 4,
/// 位5：血糖变化过快失效
/// Bit 5: Blood glucose changes too fast failure
  CGMAlarmCodeBloodGlucoseChangeTooFast = 5,
/// 位6：预留
/// Bit 6: Reserved
  CGMAlarmCodeReserved6 = 6,
/// 位7：预留
/// Bit 7: Reserved
  CGMAlarmCodeReserved7 = 7,
};

/// 复位信息
/// Reset Information
typedef SWIFT_ENUM(NSInteger, CGMResetCode, open) {
  CGMResetCodeNone = 0,
/// 霍尔唤醒
/// Hall Wakeup
  CGMResetCodeHallWakeup = 1,
/// 电池唤醒
/// Battery Wakeup
  CGMResetCodeBatteryWakeup = 2,
/// 软件唤醒
/// Software Wakeup
  CGMResetCodeSoftwareWakeup = 3,
/// 其他复位类型
/// Other Reset Types
  CGMResetCodeOther = 4,
};

/// 连接异常信息
/// Connection Error Information
typedef SWIFT_ENUM(NSInteger, ConnectErrorCode, open) {
/// sn = nil
/// sn is nil
  ConnectErrorCodeSnError = 500001,
/// 查找的设备不存在
/// Device Not Found
  ConnectErrorCodeNoDeviceError = 500002,
/// 查找的设备已过期
/// Device Expired
  ConnectErrorCodeDeviceExpiredError = 500003,
/// 蓝牙连接异常
/// Bluetooth Connection Error
  ConnectErrorCodeConnectError = 500004,
/// 连接服务异常
/// Service Discovery Error
  ConnectErrorCodeDiscoverServicesError = 500005,
/// 查找特征异常
/// Characteristic Discovery Error
  ConnectErrorCodeDiscoverCharacteristicsError = 500006,
/// 蓝牙交互异常
/// Bluetooth Communication Error
  ConnectErrorCodeBleError = 500007,
};

/// 设备连接状态枚举
/// Device Connection Status Enumeration
typedef SWIFT_ENUM(NSInteger, SOBleDeviceConnectionState, open) {
/// 未连接
/// Disconnected
  SOBleDeviceConnectionStateDisconnected = 0,
/// 连接中
/// Connecting
  SOBleDeviceConnectionStateConnecting = 1,
/// 已连接
/// Connected
  SOBleDeviceConnectionStateConnected = 2,
/// 断开中
/// Disconnecting
  SOBleDeviceConnectionStateDisconnecting = 3,
};

/// 连接过程
/// Connection Process
typedef SWIFT_ENUM(NSInteger, SOCGMConProcessState, open) {
/// 扫描设备
/// Scanning for devices
  SOCGMConProcessStateScan = 0,
/// 连接蓝牙
/// Connecting Bluetooth
  SOCGMConProcessStateConnect = 1,
/// 连接服务
/// Discovering services
  SOCGMConProcessStateDidDiscoverServices = 2,
/// 找到特征
/// Discovering characteristics
  SOCGMConProcessStateDidDiscoverCharacteristicsFor = 3,
/// 连接完成
/// Connection completed
  SOCGMConProcessStateCompleted = 4,
/// 断开连接
/// Disconnecting
  SOCGMConProcessStateDisConnect = 5,
/// 取消连接
/// Peripheral disconnected
  SOCGMConProcessStateDidDisconnectPeripheral = 6,
};

enum SOCGMSensorState : NSInteger;
@class NSString;
/// 传感器信息
/// Sensor Information
SWIFT_CLASS("_TtC15StayOnFramework15SOCGMDeviceInfo")
@interface SOCGMDeviceInfo : NSObject
@property (nonatomic, readonly) enum SOCGMSensorState sensorState;
/// 最新数据包号 数据包号以1开始
/// Latest packet ID (Packet ID starts from 1)
@property (nonatomic) NSInteger maxPacketID;
/// 血糖测量间隔 单位：秒
/// Blood glucose measurement interval, unit: seconds
@property (nonatomic) NSInteger measurementInterval;
/// 设备激活时间
/// Sensor activation time
@property (nonatomic) NSInteger sensorStartTime;
/// 固件版本号
/// Firmware version number
@property (nonatomic, copy) NSString * _Nonnull firmwareVersion;
/// 重置状态
/// Reset status
@property (nonatomic) enum CGMResetCode resetCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 传感器状态
/// Sensor Status
typedef SWIFT_ENUM(NSInteger, SOCGMSensorState, open) {
  SOCGMSensorStateUnknown = 0,
/// 预热
/// Warming Up
  SOCGMSensorStateWarmingUp = 1,
/// 已激活
/// Active
  SOCGMSensorStateActive = 2,
/// 过期（停止使用）
/// Expired (Stop using)
  SOCGMSensorStateExpired = 3,
/// 故障-异常告警（停止使用）
/// Failure - Abnormal Alarm (Stop using)
  SOCGMSensorStateFailureAlarm = 4,
/// 故障-异常重置（停止使用）
/// Failure - Abnormal Reset (Stop using)
  SOCGMSensorStateFailureReset = 5,
};

@class NSNumber;
/// 血糖数据模型
/// Blood Glucose Data Model
SWIFT_CLASS("_TtC15StayOnFramework18SOFBloodSugarModel")
@interface SOFBloodSugarModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull sn;
/// 血糖趋势 1为平稳 5为斜升 10为斜降 15为直升 20为直降
/// Blood glucose trend: 1=Stable, 5=Slightly Rising, 10=Slightly Falling, 15=Sharply Rising, 20=Sharply Falling
@property (nonatomic, copy) NSString * _Nonnull trend;
/// 数据类型 1 初始化 2 正常
/// Data type: 1=Initialization, 2=Normal
@property (nonatomic, copy) NSString * _Nonnull type;
/// 血糖产生时间（时间戳）
/// Blood glucose generation time (timestamp)
@property (nonatomic) NSInteger createTime;
/// UI血糖值（1位小数）
/// UI blood glucose value (1 decimal place)
@property (nonatomic, copy) NSString * _Nonnull bloodSugar;
/// 原始血糖值（2位小数）
/// Original blood glucose value (2 decimal places)
@property (nonatomic, copy) NSString * _Nonnull originalBloodSugar;
/// 最终血糖值（2位小数）
/// Final processed blood glucose value (2 decimal places)
@property (nonatomic, copy) NSString * _Nonnull processedBloodSugar;
/// 电流
/// Current
@property (nonatomic, copy) NSString * _Nonnull current;
/// 数据包序列号
/// Data packet serial number
@property (nonatomic) NSInteger packageNum;
/// 电压值
/// Voltage value
@property (nonatomic, copy) NSString * _Nonnull voltage;
/// 接收时间（时间戳）
/// App reception time (timestamp)
@property (nonatomic) NSInteger appTime;
/// 测量状态报警
/// Measurement status alarm
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull alarmCodeRawArr;
/// 温度
/// Temperature
@property (nonatomic, copy) NSString * _Nonnull temperature;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 传感器数据
/// Sensor Data
SWIFT_CLASS("_TtC15StayOnFramework16SOFCGMDeviceData")
@interface SOFCGMDeviceData : NSObject
/// 传感器状态
/// Sensor status
@property (nonatomic) enum SOCGMSensorState sensorState;
/// 测量状态报警
/// Measurement status alarm
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull alarmCodeRawArr;
/// 血糖数据
/// Blood glucose data
@property (nonatomic, copy) NSArray<SOFBloodSugarModel *> * _Nonnull dataList;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSData;
/// CGM核心单例
/// CGM Core Singleton
SWIFT_CLASS("_TtC15StayOnFramework13SOFCGMManager")
@interface SOFCGMManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SOFCGMManager * _Nonnull shared;)
+ (SOFCGMManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 版本号
/// Version Number
@property (nonatomic, readonly, copy) NSString * _Nonnull fullVersion;
/// 授权校验
/// Authorization Verification
/// \param apiSecret API Secret
///
/// \param apiKey API Key
///
- (void)authWithAppid:(NSString * _Nonnull)appid appsecrect:(NSString * _Nonnull)appsecrect completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
/// 绑定回调
/// Bind Callback Closures
/// \param BLEState Bluetooth state
///
/// \param cgmConState Device connection status
///
/// \param cgmConProcessState Device connection process
///
/// \param cgmDevInfo Device information
///
/// \param cgmDevData Blood glucose data
///
/// \param cgmHistoryDataProgress Historical data acquisition progress
///
/// \param failure Error information
///
- (void)addCallbackWithBLEState:(void (^ _Nonnull)(CBManagerState))BLEState cgmConState:(void (^ _Nonnull)(enum SOBleDeviceConnectionState))cgmConState cgmConProcessState:(void (^ _Nonnull)(enum SOCGMConProcessState))cgmConProcessState cgmDevInfo:(void (^ _Nonnull)(SOCGMDeviceInfo * _Nonnull))cgmDevInfo cgmDevData:(void (^ _Nonnull)(SOFCGMDeviceData * _Nonnull))cgmDevData cgmHistoryDataProgress:(void (^ _Nonnull)(float))cgmHistoryDataProgress failure:(void (^ _Nonnull)(NSError * _Nonnull))failure;
/// 取消绑定方法
/// Unbind Callback Method
- (void)cancelCallback;
/// 连接设备
/// Connect to Device
/// \param sn Device packaging SN
///
/// \param package_num Locally saved maximum packet ID
///
- (void)connectWithSn:(NSString * _Nonnull)sn package_num:(NSInteger)package_num;
/// 获取历史数据 ！！！连接设备后调用有效！！！
/// Get Historical Data !!! Valid only after connecting to device !!!
/// 在addCallback 中返回所有包号大于package_num的数据
/// Returns all data with packet ID greater than package_num in addCallback
/// \param package_num Start index
///
- (void)getHistoryDataWithPackage_num:(NSInteger)package_num;
/// 断开连接
/// Disconnect Device
- (void)disconnect;
/// 输出日志
/// Output Log
- (NSData * _Nonnull)getLog SWIFT_WARN_UNUSED_RESULT;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef STAYONFRAMEWORK_SWIFT_H
#define STAYONFRAMEWORK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreBluetooth;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="StayOnFramework",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// 接口异常信息
/// API Error Information
typedef SWIFT_ENUM(NSInteger, APIErrorCode, open) {
/// 网络异常
/// Network Error
  APIErrorCodeApiError = 400001,
/// 解析异常
/// Parsing Error
  APIErrorCodeCodeError = 400002,
/// 数据异常
/// Data Error
  APIErrorCodeDataError = 400003,
/// 缺少参数
/// Missing Parameters
  APIErrorCodeParamError = 400004,
/// 签名校验失败
/// Signature Verification Failed
  APIErrorCodeSignError = 400005,
/// 查找的信息不存在
/// Requested Data Not Found
  APIErrorCodeNoDataError = 400006,
/// token不存在
/// Token Not Found
  APIErrorCodeNoTokenError = 400007,
/// token失效
/// Token Expired
  APIErrorCodeTokenError = 400008,
};

/// 设备测量状态报警枚举
/// Device measurement status alarm enumeration
typedef SWIFT_ENUM(NSInteger, CGMAlarmCode, open) {
/// 位0：设备电量低
/// Bit 0: Low device battery
  CGMAlarmCodeLowBattery = 0,
/// 位1：温度过高
/// Bit 1: High temperature
  CGMAlarmCodeHighTemperature = 1,
/// 位2：温度过低
/// Bit 2: Low temperature
  CGMAlarmCodeLowTemperature = 2,
/// 位3：AFE异常
/// Bit 3: AFE error
  CGMAlarmCodeAfeError = 3,
/// 位4：电流过大/过小失效
/// Bit 4: Current too high/too low failure
  CGMAlarmCodeCurrentAbnormal = 4,
/// 位5：血糖变化过快失效
/// Bit 5: Blood glucose changes too fast failure
  CGMAlarmCodeBloodGlucoseChangeTooFast = 5,
/// 位6：预留
/// Bit 6: Reserved
  CGMAlarmCodeReserved6 = 6,
/// 位7：预留
/// Bit 7: Reserved
  CGMAlarmCodeReserved7 = 7,
};

/// 复位信息
/// Reset Information
typedef SWIFT_ENUM(NSInteger, CGMResetCode, open) {
  CGMResetCodeNone = 0,
/// 霍尔唤醒
/// Hall Wakeup
  CGMResetCodeHallWakeup = 1,
/// 电池唤醒
/// Battery Wakeup
  CGMResetCodeBatteryWakeup = 2,
/// 软件唤醒
/// Software Wakeup
  CGMResetCodeSoftwareWakeup = 3,
/// 其他复位类型
/// Other Reset Types
  CGMResetCodeOther = 4,
};

/// 连接异常信息
/// Connection Error Information
typedef SWIFT_ENUM(NSInteger, ConnectErrorCode, open) {
/// sn = nil
/// sn is nil
  ConnectErrorCodeSnError = 500001,
/// 查找的设备不存在
/// Device Not Found
  ConnectErrorCodeNoDeviceError = 500002,
/// 查找的设备已过期
/// Device Expired
  ConnectErrorCodeDeviceExpiredError = 500003,
/// 蓝牙连接异常
/// Bluetooth Connection Error
  ConnectErrorCodeConnectError = 500004,
/// 连接服务异常
/// Service Discovery Error
  ConnectErrorCodeDiscoverServicesError = 500005,
/// 查找特征异常
/// Characteristic Discovery Error
  ConnectErrorCodeDiscoverCharacteristicsError = 500006,
/// 蓝牙交互异常
/// Bluetooth Communication Error
  ConnectErrorCodeBleError = 500007,
};

/// 设备连接状态枚举
/// Device Connection Status Enumeration
typedef SWIFT_ENUM(NSInteger, SOBleDeviceConnectionState, open) {
/// 未连接
/// Disconnected
  SOBleDeviceConnectionStateDisconnected = 0,
/// 连接中
/// Connecting
  SOBleDeviceConnectionStateConnecting = 1,
/// 已连接
/// Connected
  SOBleDeviceConnectionStateConnected = 2,
/// 断开中
/// Disconnecting
  SOBleDeviceConnectionStateDisconnecting = 3,
};

/// 连接过程
/// Connection Process
typedef SWIFT_ENUM(NSInteger, SOCGMConProcessState, open) {
/// 扫描设备
/// Scanning for devices
  SOCGMConProcessStateScan = 0,
/// 连接蓝牙
/// Connecting Bluetooth
  SOCGMConProcessStateConnect = 1,
/// 连接服务
/// Discovering services
  SOCGMConProcessStateDidDiscoverServices = 2,
/// 找到特征
/// Discovering characteristics
  SOCGMConProcessStateDidDiscoverCharacteristicsFor = 3,
/// 连接完成
/// Connection completed
  SOCGMConProcessStateCompleted = 4,
/// 断开连接
/// Disconnecting
  SOCGMConProcessStateDisConnect = 5,
/// 取消连接
/// Peripheral disconnected
  SOCGMConProcessStateDidDisconnectPeripheral = 6,
};

enum SOCGMSensorState : NSInteger;
@class NSString;
/// 传感器信息
/// Sensor Information
SWIFT_CLASS("_TtC15StayOnFramework15SOCGMDeviceInfo")
@interface SOCGMDeviceInfo : NSObject
@property (nonatomic, readonly) enum SOCGMSensorState sensorState;
/// 最新数据包号 数据包号以1开始
/// Latest packet ID (Packet ID starts from 1)
@property (nonatomic) NSInteger maxPacketID;
/// 血糖测量间隔 单位：秒
/// Blood glucose measurement interval, unit: seconds
@property (nonatomic) NSInteger measurementInterval;
/// 设备激活时间
/// Sensor activation time
@property (nonatomic) NSInteger sensorStartTime;
/// 固件版本号
/// Firmware version number
@property (nonatomic, copy) NSString * _Nonnull firmwareVersion;
/// 重置状态
/// Reset status
@property (nonatomic) enum CGMResetCode resetCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 传感器状态
/// Sensor Status
typedef SWIFT_ENUM(NSInteger, SOCGMSensorState, open) {
  SOCGMSensorStateUnknown = 0,
/// 预热
/// Warming Up
  SOCGMSensorStateWarmingUp = 1,
/// 已激活
/// Active
  SOCGMSensorStateActive = 2,
/// 过期（停止使用）
/// Expired (Stop using)
  SOCGMSensorStateExpired = 3,
/// 故障-异常告警（停止使用）
/// Failure - Abnormal Alarm (Stop using)
  SOCGMSensorStateFailureAlarm = 4,
/// 故障-异常重置（停止使用）
/// Failure - Abnormal Reset (Stop using)
  SOCGMSensorStateFailureReset = 5,
};

@class NSNumber;
/// 血糖数据模型
/// Blood Glucose Data Model
SWIFT_CLASS("_TtC15StayOnFramework18SOFBloodSugarModel")
@interface SOFBloodSugarModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull sn;
/// 血糖趋势 1为平稳 5为斜升 10为斜降 15为直升 20为直降
/// Blood glucose trend: 1=Stable, 5=Slightly Rising, 10=Slightly Falling, 15=Sharply Rising, 20=Sharply Falling
@property (nonatomic, copy) NSString * _Nonnull trend;
/// 数据类型 1 初始化 2 正常
/// Data type: 1=Initialization, 2=Normal
@property (nonatomic, copy) NSString * _Nonnull type;
/// 血糖产生时间（时间戳）
/// Blood glucose generation time (timestamp)
@property (nonatomic) NSInteger createTime;
/// UI血糖值（1位小数）
/// UI blood glucose value (1 decimal place)
@property (nonatomic, copy) NSString * _Nonnull bloodSugar;
/// 原始血糖值（2位小数）
/// Original blood glucose value (2 decimal places)
@property (nonatomic, copy) NSString * _Nonnull originalBloodSugar;
/// 最终血糖值（2位小数）
/// Final processed blood glucose value (2 decimal places)
@property (nonatomic, copy) NSString * _Nonnull processedBloodSugar;
/// 电流
/// Current
@property (nonatomic, copy) NSString * _Nonnull current;
/// 数据包序列号
/// Data packet serial number
@property (nonatomic) NSInteger packageNum;
/// 电压值
/// Voltage value
@property (nonatomic, copy) NSString * _Nonnull voltage;
/// 接收时间（时间戳）
/// App reception time (timestamp)
@property (nonatomic) NSInteger appTime;
/// 测量状态报警
/// Measurement status alarm
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull alarmCodeRawArr;
/// 温度
/// Temperature
@property (nonatomic, copy) NSString * _Nonnull temperature;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 传感器数据
/// Sensor Data
SWIFT_CLASS("_TtC15StayOnFramework16SOFCGMDeviceData")
@interface SOFCGMDeviceData : NSObject
/// 传感器状态
/// Sensor status
@property (nonatomic) enum SOCGMSensorState sensorState;
/// 测量状态报警
/// Measurement status alarm
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull alarmCodeRawArr;
/// 血糖数据
/// Blood glucose data
@property (nonatomic, copy) NSArray<SOFBloodSugarModel *> * _Nonnull dataList;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSData;
/// CGM核心单例
/// CGM Core Singleton
SWIFT_CLASS("_TtC15StayOnFramework13SOFCGMManager")
@interface SOFCGMManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SOFCGMManager * _Nonnull shared;)
+ (SOFCGMManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 版本号
/// Version Number
@property (nonatomic, readonly, copy) NSString * _Nonnull fullVersion;
/// 授权校验
/// Authorization Verification
/// \param apiSecret API Secret
///
/// \param apiKey API Key
///
- (void)authWithAppid:(NSString * _Nonnull)appid appsecrect:(NSString * _Nonnull)appsecrect completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
/// 绑定回调
/// Bind Callback Closures
/// \param BLEState Bluetooth state
///
/// \param cgmConState Device connection status
///
/// \param cgmConProcessState Device connection process
///
/// \param cgmDevInfo Device information
///
/// \param cgmDevData Blood glucose data
///
/// \param cgmHistoryDataProgress Historical data acquisition progress
///
/// \param failure Error information
///
- (void)addCallbackWithBLEState:(void (^ _Nonnull)(CBManagerState))BLEState cgmConState:(void (^ _Nonnull)(enum SOBleDeviceConnectionState))cgmConState cgmConProcessState:(void (^ _Nonnull)(enum SOCGMConProcessState))cgmConProcessState cgmDevInfo:(void (^ _Nonnull)(SOCGMDeviceInfo * _Nonnull))cgmDevInfo cgmDevData:(void (^ _Nonnull)(SOFCGMDeviceData * _Nonnull))cgmDevData cgmHistoryDataProgress:(void (^ _Nonnull)(float))cgmHistoryDataProgress failure:(void (^ _Nonnull)(NSError * _Nonnull))failure;
/// 取消绑定方法
/// Unbind Callback Method
- (void)cancelCallback;
/// 连接设备
/// Connect to Device
/// \param sn Device packaging SN
///
/// \param package_num Locally saved maximum packet ID
///
- (void)connectWithSn:(NSString * _Nonnull)sn package_num:(NSInteger)package_num;
/// 获取历史数据 ！！！连接设备后调用有效！！！
/// Get Historical Data !!! Valid only after connecting to device !!!
/// 在addCallback 中返回所有包号大于package_num的数据
/// Returns all data with packet ID greater than package_num in addCallback
/// \param package_num Start index
///
- (void)getHistoryDataWithPackage_num:(NSInteger)package_num;
/// 断开连接
/// Disconnect Device
- (void)disconnect;
/// 输出日志
/// Output Log
- (NSData * _Nonnull)getLog SWIFT_WARN_UNUSED_RESULT;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
